// drills/version-1/drill1vue/src/components/JobList.vue
<template>
  <section>
    <h2>Job Listings</h2>
    <ul id="job-listings" v-for="job in jobs" v-bind:key="job.id">
      <li>
        <h4>{{ job.title }}</h4>
        <small>{{ job.pay }}</small>
        <p>{{ job.description }}</p>
        <small
          >{{
            job.interested.length > 1
              ? job.interested.length + " dinos are"
              : "1 dino is"
          }}
          interested in this job</small
        >
      </li>
    </ul>
  </section>
</template>

<script>
export default {
  name: "JobList",
  props: ["jobs"],
};
</script>

// drills/version-1/drill1reacttypescript/src/components/JobList.tsx
import React from 'react';
import { JobListing, Jobs } from '../App';

interface JobListProps {
    postings: Jobs
}
export const JobList = ({postings}: JobListProps) => {
    const items = postings.jobs.map((job: JobListing) => {
        return (
            <li key={job.id}>
                <h4>{job.title}</h4>
                <small>{job.pay}</small>
                <p>{job.description}</p>
                <small>{job.interested.length > 1 ? job.interested.length + ' dinos are' : '1 dino is'} interested in this job</small>
            </li>
        )
    })

    return (
        <section>
            <h2>Job Postings</h2>
            <ul id="job-listings">
                {items}
            </ul>
        </section>
    )
}

export default JobList;
