// drills/version-1/drill1angular/src/app/components/add-a-job-form/add-a-job-form.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { FormGroup, NgForm } from '@angular/forms';
@Component({
  selector: 'app-add-a-job-form',
  templateUrl: './add-a-job-form.component.html',
  styleUrls: ['./add-a-job-form.component.css']
})
export class AddAJobFormComponent implements OnInit {

  @Input() dataObject;
  form: FormGroup;
  ngOnInit() {
  }
  onSubmit(form: NgForm) {
    console.log(form.value);
    console.log(this.dataObject);
    let interested = 1;
    if (form.value.interested == undefined) {
      form.value.interested =[interested];
    } 
    form.value.interested = [1];
    this.dataObject.map(function(job) {
      if (form.value.title == job.title) {

        form.value.interested.push("MATCH FOUND")
      }
    })

    this.dataObject.unshift(form.value);
  }
}

<aside id="side-bar">
  <h3>Add a Job</h3>
  <form class="job-form" (ngSubmit)='onSubmit(f)' #f='ngForm'>
    <div class="form-group">
    <label for="title">Title</label>
    <input 
      type="text" 
      id="title"
      class="form-control"
      ngModel
      name="title">
    </div>

    <div class="form-group">
    <label for="pay">Compensation</label>
    <input 
      type="text" 
      id="pay"
      class="form-control"
      ngModel
      name="pay">
    </div>

    <div class="form-group">
    <label for="description">Description</label>
    <textarea 
      id="description"
      name="description" 
      class="form-control"
      ngModel
      rows="8" 
      cols="40"></textarea>
    </div>

    <input 
      type="submit" 
      id="submit"
      class="form-control"
      ngModel="Submit"
      name="submit" 
      value="Submit" />
  </form>
</aside>

// drills/version-1/drill1vue-composition-api/src/components/AddAJobForm.vue
<template>
  <aside id="side-bar">
    <h3>Add a Job</h3>
    <form class="job-form" @submit.prevent="addJob">
      <label for="title">Title</label>
      <input type="text" v-model="title" name="title" />
      <label for="pay">Compensation</label>
      <input type="text" v-model="pay" name="pay" />
      <label for="description">Description</label>
      <textarea
        name="description"
        v-model="description"
        rows="8"
        cols="40"
      ></textarea>
      <input type="submit" name="submit" value="Submit" />
    </form>
  </aside>
</template>

<script>
    import { ref } from 'vue';
    export default {
        setup(props, { emit }) {
            const title = ref('');
            const pay = ref('');
            const description = ref('');

            const addJob = () => {
                const newJob = {
                    title: title.value,
                    pay: pay.value,
                    description: description.value,
                    interested: [],
                };

                emit('add-job', newJob);
                title.value = '';
                pay.value = '';
                description.value = '';
            }

            return {
                title,
                pay,
                description,
                addJob
            }

        }
    }
</script>
