// drills/version-1/drill1vue-composition-api/src/components/JobList.vue
<template>
  <section>
    <h2>Job Listings</h2>
    <ul id="job-listings" v-for="job in jobs" :key="job.id">
      <li>
        <h4>{{ job.title }}</h4>
        <small>{{ job.pay }}</small>
        <p>{{ job.description }}</p>
        <small
          >{{
            job.interested.length > 1
              ? job.interested.length + " dinos are"
              : "1 dino is"
          }}
          interested in this job</small
        >
      </li>
    </ul>
  </section>
</template>

<script>

export default {
    props: [
        'jobs'
    ]
};
</script>

// drills/version-1/drill1angular/src/app/components/job-list/job-list.component.ts
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'app-job-list',
  templateUrl: './job-list.component.html',
  styleUrls: ['./job-list.component.css']
})
export class JobListComponent implements OnInit {
  public h2Title = "Job Listings";
  @Input() jobs;
  ngOnInit() {
    
  }

}

<section>
  <h2>{{h2Title}}</h2>
  <ul id="job-listings">
    <li *ngFor="let job of jobs">
      <h4>{{job.title}}</h4>
      <small>{{job.pay}}</small>
      <p>{{job.description}}</p>
      <small *ngIf="job.interested.length !==1">{{job.interested.length}} dinos are interested in this job</small>
      <small *ngIf="job.interested.length == 1">{{job.interested.length}} dino is interested in this job</small>
    </li>
  </ul>
</section>
